blog/urls.py
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("", views.ArticlesListView.as_view(), name="article_list"),
    path("article/<slug:slug>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("articles_by_author/<str:username>/", views.ArticlesByUser.as_view(), name="articles_by_user"),
    path("articles_by_you/", views.ArticlesByCurrentUser.as_view(), name="articles_by_current_user"),
    path("article_by_category/<slug:category_slug>/", views.ArticlesByCategoryListView.as_view(), name="articles_by_category"),
    path("article_by_tag/<slug:tag_slug>/", views.ArtcilesByTag.as_view(), name="articles_by_tag"),
    path("create_article/", views.ArticleCreateView.as_view(), name="create_article"),
    path("article_delete_confirm/<slug:slug>/", views.ArticleDelete.as_view(), name="delete_article_confirm"),
    path("article_edit/<slug:slug>/", views.ArticleUpdate.as_view(), name="article_edit"),
    path("add_comment/<str:article_slug>/", views.AddComment.as_view(), name="add_comment"),
    path("article_search/", views.ArticleSearch.as_view(), name="article_search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_account import views as user_account_views
from .yasg import urlpatterns as doc_urls
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/signin/", user_account_views.LoginView.as_view(), name="signin"),
    path("accounts/signup/", user_account_views.RegisterCreateView.as_view(), name="signup"),
    path("accounts/signout/", LogoutView.as_view(), name="some"),
    path("accounts/",  include("django.contrib.auth.urls")),
    path("accounts/", include("user_account.urls", namespace="user_profile")),
    path("api-auth/", include("djoser.urls")),
    path("api-auth/", include("djoser.urls.authtoken")),
    path("api-auth/", include("djoser.urls.jwt")),
    path("api/v1/user_account/", include("user_account.api.urls")),
    path("api/v1/blog/", include("blog.api.urls")),
    path("", include("blog.urls", namespace="blog")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]


urlpatterns += doc_urls


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_account/urls.py
from django.urls import path
from . import views


app_name = "user_account"


urlpatterns = [
    path("profiles/", views.UserProfileListView.as_view(), name="profiles"),
    path("profile/<str:username>/" , views.UserProfileView.as_view(), name="profile"),
    path("profile/<str:username>/update/", views.UserDataUpdateView.as_view(), name="update_profile"),
    path("user_search/", views.UserProfileSearch.as_view(), name="search_user"),
    path("add_social_network_link/<str:soc_net_name>/", views.AddSocialNetworkLink.as_view(), name="add_soc_net_link"),
    path("delete_social_link/<str:soc_net_name>/", views.DeleteSocialNetworkLink.as_view(), name="delete_soc_link"),
]

templates/user_profile/add_soc_net_link.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add link{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input class="btn btn-success" type="submit" value="Save">
    </form>
{% endblock content %}

templates/user_profile/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load user_account_tags %}

{% block title %}
	{% if section is not None %}
		My profile
	{% else %}
		{% if user_profile.user.get_full_name %}
			{{ user_profile.user.get_full_name }}
		{% else %}
			{{ user_profile.user.username }}
		{% endif %}
	{% endif %}
{% endblock title %}

{% block content %}
<div class="container">
	<div class="main-body">
		<div class="row gutters-sm">
			<div class="col-md-4 mb-3">
				<div class="card">
					<div class="card-body">
						<div class="d-flex flex-column align-items-center text-center">
							{% if user_profile.avatar %}
								<!-- <img src="{{ user_profile.avatar.url }}" class="img-thumbnail"> -->
								{% thumbnail user_profile.avatar "270x270" as im %}
									<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
								{% endthumbnail %}
							{% else %}
								<img src="{% static 'images/none.png' %}" width="270" height="270">
							{% endif %}
							<div class="mt-3">
								<h4>
									{% if user_profile.user.get_full_name %}
										{{ user_profile.user.get_full_name }}
									{% else %}
										user_profile.user.username }}
									{% endif %}
								</h4>
								<p class="text-secondary mb-1">{{ user_profile.bio }}</p>
							</div>
							<h3>Email</h3>
								{{ user_profile.user.email }}
							<hr>
						</div>
					</div>
				</div>
				<br>
				{% if request.user == user_profile.user %}
					<div class="card">
						<a href="{% url 'user_account:update_profile' request.user.username %}" class="btn btn-primary">Update Profile</a>
						<br>
						<a href="{% url 'password_change' %}" class="btn btn-primary">Change password</a>
					</div>
				{% endif %}
				<div class="card mt-3">
					<ul class="list-group list-group-flush">
						{% get_link user_profile 'pers_website' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/ios-filled/30/000000/domain.png"/>Website</h6>
									<span class="text-secondary">{{ link }}</span>	
								</li>	
								<a href="{% url 'user_account:delete_soc_link' 'pers_website' %}" class="btn btn-danger">Delete link</a>	
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/ios-filled/30/000000/domain.png"/>Website</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'pers_website' %}">Add link</a>
								{% endif %}
							{% endif %}
						{% get_link user_profile 'mail' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/fluency/30/000000/apple-mail.png"/>/>Mail</h6>
									<span class="text-secondary">{{ link }}</span>	
								</li>	
								<a href="{% url 'user_account:delete_soc_link' 'mail' %}" class="btn btn-danger">Delete link</a>	
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/fluency/30/000000/apple-mail.png"/>Mail</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'mail' %}">Add link</a>
								{% endif %}
							{% endif %}
						{% get_link user_profile 'telegram' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/telegram-app--v3.png"/>Telegram</h6>
									<span class="text-secondary">{{ link }}</span>
								</li>
								<a href="{% url 'user_account:delete_soc_link' 'telegram' %}" class="btn btn-danger">Delete link</a>
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/telegram-app--v3.png"/>Telegram</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'telegram' %}">Add link</a>
								{% endif %}
							{% endif %}
						{% get_link user_profile 'git' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/windows/30/000000/github.png"/>Github</h6>
									<span class="text-secondary">{{ link }}</span>
								</li>
								<a href="{% url 'user_account:delete_soc_link' 'git' %}" class="btn btn-danger">Delete link</a>
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/windows/30/000000/github.png"/>GitHub</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'git' %}">Add link</a>
								{% endif %}
							{% endif %}
						{% get_link user_profile 'linkin' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/linkedin.png"/>LinkedIn</h6>
									<span class="text-secondary">{{ link }}</span>
								</li>
								<a href="{% url 'user_account:delete_soc_link' 'linkin' %}" class="btn btn-danger">Delete link</a>
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/linkedin.png"/>LinkedIn</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'linkin' %}">Add link</a>
								{% endif %}
							{% endif %}
						{% get_link user_profile 'twitter' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/twitter--v1.png"/>Twitter</h6>
									<span class="text-secondary">{{ link }}</span>
								</li>
								<a href="{% url 'user_account:delete_soc_link' 'twitter' %}" class="btn btn-danger">Delete link</a>
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/twitter--v1.png"/>Twitter</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'twitter' %}">Add link</a>
								{% endif %}
							{% endif %}
						{% get_link user_profile 'insta' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/fluency/30/000000/instagram-new.png"/>Instagram</h6>
									<span class="text-secondary">{{ link }}</span>
								</li>
								<a href="{% url 'user_account:delete_soc_link' 'insta' %}" class="btn btn-danger">Delete link</a>
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/fluency/30/000000/instagram-new.png"/>Instagram</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'insta' %}">Add link</a>
								{% endif %}
							{% endif %}
						{% get_link user_profile 'facebook' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/facebook.png"/>Facebook</h6>
									<span class="text-secondary">{{ link }}</span>
								</li>
								<a href="{% url 'user_account:delete_soc_link' 'facebook' %}" class="btn btn-danger">Delete link</a>
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/facebook.png"/>Facebook</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'facebook' %}">Add link</a>
								{% endif %}
							{% endif %}
						{% get_link user_profile 'vk' as link %}
							{% if link != False %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/vk-com.png"/>VKontakte</h6>
									<span class="text-secondary">{{ link }}</span>
								</li>
								<a href="{% url 'user_account:delete_soc_link' 'vk' %}" class="btn btn-danger">Delete link</a>
							{% else %}
								<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
									<h6 class="mb-0"><img src="https://img.icons8.com/color/30/000000/vk-com.png"/>VKontakte</h6>
								</li>
								{% if request.user == user_profile.user %}
										<a class="btn btn-primary" href="{% url 'user_account:add_soc_net_link' 'vk' %}">Add link</a>
								{% endif %}
							{% endif %}
					</ul>
				</div>
			</div>
			<div class="col-md-8">
				<div class="card mb-3">
				</div>
				<h3>Last articles</h3>
				<div class="card-group">
					{% for article in last_two_articles %}
					<div class="col-lg-6">
						<div class="card mb-4">
							{% if article.image %}
								<a href="{{ article.get_absolute_url }}"><img class="card-img-top"
									src="{{ article.image.url }}"></a>
							{% endif %}
							<div class="card-body">
								<div class="small text-muted">{{ article.published|date:"f a l F Y" }}</div>
								<h2 class="card-title h4">{{ article.title }}</h2>
								<p class="card-text">{{ article.text_body|truncatewords:30|safe }}</p>
								<a class="btn btn-primary" href="{{ article.get_absolute_url }}">Read more →</a>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
				{% if request.user.username == user_profile.user.username %}
					<a href="{% url 'blog:articles_by_current_user' %}" class="btn btn-outline-primary">All my articles</a>
					<a href="{% url 'blog:create_article' %}" class="btn btn-success">Create new article</a>
				{% else %}
					<a href="{% url 'blog:articles_by_user' user_profile.user.username %}" class="btn btn-outline-primary">All author articles</a>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock content %}

templates/user_profile/user_profile_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}

{% block title %}My Blog{% endblock title %}

{% block content %}
   
    <main>
        <br>
        <br>
        <form method="get" action="{% url 'user_account:search_user' %}">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Search users" aria-describedby="button-addon2" name="q">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
            </div>
        </form>
        <div class="album py-5 bg-light">
            <div class="container">
                 <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for user_profile in user_profiles %}
                        <div class="card" style="width: 18rem;">
                            {% if user_profile.avatar %}
                                <a href="{% url 'user_account:profile' user_profile.user.username %}">
                                    <img src="{{ user_profile.avatar.url }}">
                                </a>
                            {% else %}
                                <a href="{% url 'user_account:profile' user_profile.user.username %}"><img src="{% static 'images/avatar.png' %}"></a>
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">
                                    {% if user_profile.user.get_full_name %}
                                        {{ user_profile.user.get_full_name }}
                                    {% else %}
                                        {{ user_profile.user.username }}
                                    {% endif %}
                                </h5>
                                {% if user_profile.bio %}
                                    <p class="card-text">{{ user_profile.bio }}</p>
                                {% endif %}
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">{{ user_profile.user.email }}</li>
                            </ul>
                            <div class="card-body">
                                <a href="{% url 'user_account:profile' user_profile.user.username %}" class="btn btn-outline-primary">view</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <br>
                <br>
                {% include 'components/pagination.html' %}
            </div>
        </div> 
 
    </main>
{% endblock content %}
    

templates/user_profile/user_profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update profile{% endblock title %}

{% block content %}
	<h1>Update profile</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ user_form|crispy  }}	
		{{ user_profile_form|crispy }} 
		<br>
		<input class="btn btn-success" type="submit" value="Update">
	</form>
{% endblock content %}