blog/urls.py
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("", views.ArticlesListView.as_view(), name="article_list"),
    path("article/<slug:slug>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("articles_by_author/<str:username>/", views.ArticlesByUser.as_view(), name="articles_by_user"),
    path("articles_by_you/", views.ArticlesByCurrentUser.as_view(), name="articles_by_current_user"),
    path("article_by_category/<slug:category_slug>/", views.ArticlesByCategoryListView.as_view(), name="articles_by_category"),
    path("article_by_tag/<slug:tag_slug>/", views.ArtcilesByTag.as_view(), name="articles_by_tag"),
    path("create_article/", views.ArticleCreateView.as_view(), name="create_article"),
    path("article_delete_confirm/<slug:slug>/", views.ArticleDelete.as_view(), name="delete_article_confirm"),
    path("article_edit/<slug:slug>/", views.ArticleUpdate.as_view(), name="article_edit"),
    path("add_comment/<str:article_slug>/", views.AddComment.as_view(), name="add_comment"),
    path("article_search/", views.ArticleSearch.as_view(), name="article_search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_account import views as user_account_views
from .yasg import urlpatterns as doc_urls
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/signin/", user_account_views.LoginView.as_view(), name="signin"),
    path("accounts/signup/", user_account_views.RegisterCreateView.as_view(), name="signup"),
    path("accounts/signout/", LogoutView.as_view(), name="some"),
    path("accounts/",  include("django.contrib.auth.urls")),
    path("accounts/", include("user_account.urls", namespace="user_profile")),
    path("api-auth/", include("djoser.urls")),
    path("api-auth/", include("djoser.urls.authtoken")),
    path("api-auth/", include("djoser.urls.jwt")),
    path("api/v1/user_account/", include("user_account.api.urls")),
    path("api/v1/blog/", include("blog.api.urls")),
    path("", include("blog.urls", namespace="blog")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]


urlpatterns += doc_urls


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_account/urls.py
from django.urls import path
from . import views


app_name = "user_account"


urlpatterns = [
    path("profiles/", views.UserProfileListView.as_view(), name="profiles"),
    path("profile/<str:username>/" , views.UserProfileView.as_view(), name="profile"),
    path("profile/<str:username>/update/", views.UserDataUpdateView.as_view(), name="update_profile"),
    path("user_search/", views.UserProfileSearch.as_view(), name="search_user"),
    path("add_social_network_link/<str:soc_net_name>/", views.AddSocialNetworkLink.as_view(), name="add_soc_net_link"),
    path("delete_social_link/<str:soc_net_name>/", views.DeleteSocialNetworkLink.as_view(), name="delete_soc_link"),
]

templates/components/header.html
<main>
    <header class="p-3 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                  <h4><a class="nav-link px-2 text-white" href="{% url 'blog:article_list' %}">My blog</a></h4>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    {% if request.user.is_authenticated %}
                        <h5><li><a {% if section == 'my_profile' %}class="nav-link px-2 text-white" {% else %}class="nav-link px-2 text-secondary"
                            {% endif %} href="{% url 'user_account:profile' request.user.username %}">My profile</a></li></h5>
                    {% else %}
                        <h5><li><a href="{% url 'signin' %}" class="nav-link px-2 text-secondary">My profile</a></li></h5>
                    {% endif %}
                    <h5><li><a {% if section == 'users' %}class="nav-link px-2 text-white" {% else %}class="nav-link px-2 text-secondary"
                        {% endif %} href="{% url 'user_account:profiles' %}" class="nav-link px-2 text-secondary">Users</a></li></h5>
                </ul>
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" method="get" action="{% url 'blog:article_search' %}">
                    <input type="" class="form-control" placeholder="Search articles" aria-label="Search" name="q">
                </form>
                <div class="text-end">
                    {% if section != 'login' %}
                        {% if request.user.is_authenticated %}
                            <a class="btn btn-warning" href="{% url 'some' %}">SignOut</a>
                        {% else %}
                            <a class="btn btn-success" href="{% url 'signin' %}">SignIn</a>
                            <a href="{% url 'signup' %}" class="btn btn-warning">SignUp</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
</main>

templates/components/message.html
{% if messages %}
        
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} m-2" id='msg' role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    
{% endif %}

templates/components/nav.html
{% load article_tags %}
{% get_categories as categories %}
<div class="col-lg-4">
    <br>
    <div class="card mb-4">
        <div class="card-header">Categories</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <ul class="list-unstyled mb-0">
                        {% for category in categories %}
                            <li><a href="{% url 'blog:articles_by_category' category.slug %}">{{ category.name|title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Side widget-->
    <div class="card mb-4">
        <div class="card-header">Welcome My Blog</div>
        <div class="card-body">Welcome to My Blog, my first site to showcase my capabilities.</div>
    </div>
</div>

templates/components/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% if q %}q={{ q }}&{% endif %}page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        {% endif %}
        {% if paginator.page_range|length > 1 %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="?{% if q %}q={{ q }}&{% endif %}page={{ i }}">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?{% if q %}q={{ q }}&{% endif %}page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% if q %}q={{ q }}&{% endif %}page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span class="sr-only">Next</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>