blog/urls.py
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("", views.ArticlesListView.as_view(), name="article_list"),
    path("article/<slug:slug>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("articles_by_author/<str:username>/", views.ArticlesByUser.as_view(), name="articles_by_user"),
    path("articles_by_you/", views.ArticlesByCurrentUser.as_view(), name="articles_by_current_user"),
    path("article_by_category/<slug:category_slug>/", views.ArticlesByCategoryListView.as_view(), name="articles_by_category"),
    path("article_by_tag/<slug:tag_slug>/", views.ArtcilesByTag.as_view(), name="articles_by_tag"),
    path("create_article/", views.ArticleCreateView.as_view(), name="create_article"),
    path("article_delete_confirm/<slug:slug>/", views.ArticleDelete.as_view(), name="delete_article_confirm"),
    path("article_edit/<slug:slug>/", views.ArticleUpdate.as_view(), name="article_edit"),
    path("add_comment/<str:article_slug>/", views.AddComment.as_view(), name="add_comment"),
    path("article_search/", views.ArticleSearch.as_view(), name="article_search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_account import views as user_account_views
from .yasg import urlpatterns as doc_urls
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/signin/", user_account_views.LoginView.as_view(), name="signin"),
    path("accounts/signup/", user_account_views.RegisterCreateView.as_view(), name="signup"),
    path("accounts/signout/", LogoutView.as_view(), name="some"),
    path("accounts/",  include("django.contrib.auth.urls")),
    path("accounts/", include("user_account.urls", namespace="user_profile")),
    path("api-auth/", include("djoser.urls")),
    path("api-auth/", include("djoser.urls.authtoken")),
    path("api-auth/", include("djoser.urls.jwt")),
    path("api/v1/user_account/", include("user_account.api.urls")),
    path("api/v1/blog/", include("blog.api.urls")),
    path("", include("blog.urls", namespace="blog")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]


urlpatterns += doc_urls


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_account/urls.py
from django.urls import path
from . import views


app_name = "user_account"


urlpatterns = [
    path("profiles/", views.UserProfileListView.as_view(), name="profiles"),
    path("profile/<str:username>/" , views.UserProfileView.as_view(), name="profile"),
    path("profile/<str:username>/update/", views.UserDataUpdateView.as_view(), name="update_profile"),
    path("user_search/", views.UserProfileSearch.as_view(), name="search_user"),
    path("add_social_network_link/<str:soc_net_name>/", views.AddSocialNetworkLink.as_view(), name="add_soc_net_link"),
    path("delete_social_link/<str:soc_net_name>/", views.DeleteSocialNetworkLink.as_view(), name="delete_soc_link"),
]

templates/article/article_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete {{ article }}{% endblock title %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		<p>Are you sure you want to delete "{{ article.title }}"?</p>
		<input class="btn btn-danger" type="submit" value="Delete">
		<a class="btn btn-success" href="{{ article.get_absolute_url }}">Cancel</a>
	</form>
{% endblock content %}

templates/article/article_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Create new article{% endblock title %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <input type="submit" class="btn btn-success" value="Create">
    </form>
{% endblock content %}

templates/article/article_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load article_tags %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                <!-- Post content-->
                <article>
                    <!-- Post header-->
                    <header class="mb-4">
                        <!-- Post title-->
                        <h1 class="fw-bolder mb-1">{{ article.title }}</h1>
                        <!-- Post meta content-->
                        <div class="text-muted fst-italic mb-2">Posted at {{ article.published|date:"f a l F Y" }}</div>
                        <!-- Post categories-->
                        {% for article_tag in article.tags.all  %}
                            <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'blog:articles_by_tag' article_tag.slug %}">#{{ article_tag.name }}</a>
                        {% endfor %}
                        <hr>
                        <div class="card w-75">
                            <div class="card-body">
                              <h5 class="card-title">Author: <a href="{% url 'user_account:profile' article.author.username %}">{{ article.author.get_full_name }}</a></h5>
                              <a href="{% url 'blog:articles_by_user' article.author.username %}" class="btn btn-primary">Author articles -></a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Category: {{ article.category.name }}</h5>
                                <a href="{% url 'blog:articles_by_category' article.category.slug %}" class="btn btn-primary">Category articles -></a>
                            </div>
                        </div>
                    </header>
                    <!-- Preview image figure-->
                    <figure class="mb-4">
                        {% thumbnail article.image "1000x500" as image %}
                            <img src="{{ image.url }}">
                        {% endthumbnail %}
                    </figure>
                    <!-- Post content-->
                    <section class="mb-5">
                        <p class="fs-5">{{ article.text_body|safe }}</p>
                    </section>
                </article>
                <!-- Comments section-->
                <section class="mb-5">
                    <div class="card bg-light">
                        <div class="card-body">
                            <!-- Comment form-->
                            <form class="mb-4" method="post" action="{% url 'blog:add_comment' article.slug %}">
                                {% csrf_token %}
                                {{ comment_form.as_p }}
                                <input class="btn btn-success" type="submit" value="comment">
                            </form>
                            <!-- Comment with nested comments-->
                            {% for comment in article.get_last_five_comments %}
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0">
                                        {% thumbnail comment.author.user_profile.avatar "50x50" crop="center" as avatar %}
                                            <img src="{{ avatar.url }}">
                                        {% endthumbnail %}
                                    </div>
                                    <div class="ms-3">
                                        <div class="fw-bold">{{ comment.author }}</div>
                                        {{ comment.text_body }}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </section>
            </div>
            {% include 'components/nav.html' %}
        </div>
    </div>
    {% if request.user == article.author %}
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <a href="{% url 'blog:delete_article_confirm' article.slug %}"><button type="button" class="btn btn-danger">Delete</button></a>
            <a href="{% url 'blog:article_edit' article.slug %}"><button type="button" class="btn btn-primary">Edit</button></a>
        </div>
    {% endif %} 
{% endblock content %}

templates/article/article_list.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block title %}My Blog{% endblock title %}

{% block content %}
    {% if articles %}
            {% if current_category %}
                <h1>Article by category: {{ current_category.name }}</h1>
            {% elif author %}
                <h1>Articles by: {{ author }}</h1>
            {% elif tag %}
                <h1>Articles with tag: #{{ tag.name }}</h1>
            {% elif current_author %}
                {% if not articles %}
                    <h1>Your haven't articles.Create article <a href="{% url 'blog:create_article' %}"><button type="button"
                        class="btn btn-success">Create</button></a></h1>
                {% else %}
                    <h1>Your posts</h1>
                {% endif %}
            {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="card mb-3">
                    </div>
                    <div class="card-group">
                        {% for article in articles %}
                            <div class="col-lg-6">
                                <div class="card mb-4">
                                    {% if article.image %}
                                        <a href="{{ article.get_absolute_url }}"><img class="card-img-top"
                                            src="{{ article.image.url }}"></a>
                                    {% endif %}
                                    <div class="card-body">
                                        <div class="small text-muted">{{ article.published|date:"f a l F Y" }}</div>
                                        <h2 class="card-title h4">{{ article.title }}</h2>
                                        <p class="card-text">{{ article.text_body|truncatewords:30|safe }}</p>
                                        <a class="btn btn-primary" href="{{ article.get_absolute_url }}">Read more →</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% include 'components/pagination.html' %}
                </div>
                
                {% include 'components/nav.html' %}
            </div>
        </div>
    {% else %}
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Not have articles</h1>
                </div>
            </div>
        </header>
    {% endif %}
{% endblock content %}

templates/article/article_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Edit {{ article.title }}{% endblock title %}

{% block content %}
	<form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.media }}
		{{ form|crispy }}
		<input class="btn btn-success" type="submit" value="Save">
	</form>
{% endblock content %} -->